### ISSUE TITLE
How I can use this in android studio?

### ISSUE THREAD

**Issue by Zane96** [emicklei/rendersnake#7]
I copy the rendersnake file to my project in android studio. But I can't use this library because it has too many issues like not found some jar, 

So how can I use this in my android studio project????

**Comment by emicklei** [comment]
There are a few other dependencies you need. Can you show me the errors ? snapshot will do. AFAIK others have been able to use this for Android projects.

**Comment by Zane-cqupt** [comment]
I copy your main file in your rendersnake file to my android project.
The issue like this:
![h4_8x c 6f itu brwon](https://cloud.githubusercontent.com/assets/12124524/9698010/08767954-53d8-11e5-97e3-a0148207caf3.png)

I think there are two kind of issues.
One like this :
![6j 8 mp 6idlphr9d0efl5](https://cloud.githubusercontent.com/assets/12124524/9698024/6b26bfd2-53d8-11e5-9207-ff058a41ee3f.png)
I can work out it by changing its package name like this:
![v md 2s1k _cqz jx4ym](https://cloud.githubusercontent.com/assets/12124524/9698039/9aeced90-53d8-11e5-8f44-642f6bc0540c.png)

another one like this:
![x7 456ixvtlzr j smr 5](https://cloud.githubusercontent.com/assets/12124524/9698050/bdafebe8-53d8-11e5-9a87-e82443a661f4.png)

Should I to import these library by myself?

**Comment by Zane-cqupt** [comment]
Sorry, I'm a new coder and not good at English, maybe u can't understand my words.If u can't understand what I said , please tell me,,,thanks

**Comment by Zane-cqupt** [comment]
yeah , I have import some dependencies 
![72 c k t8 w 7 cak ixd](https://cloud.githubusercontent.com/assets/12124524/9698086/1423bf44-53da-11e5-8117-04b2a734cb29.png)

**Comment by emicklei** [comment]
Many of the dependencies your are listing here are only required if you actually use the ext.* packages. (ext referes to integrations with external frameworks such as guice, spring, servlet etc).

The core of rendersnake does not require these. Instead the only ones needed are commons-lang3 and commons-io as I recall.  You should change your Android project such that only these are loaded/needed.

**Comment by Zane-cqupt** [comment]
Thanks, u mean I should delet the ext file in main file when I copy the main file?

**Comment by emicklei** [comment]
If you are going to use the sources as is then yes, remove those subdir. If however you are going to use the JAR component as a dependency then you have much less work to do. Based on what classes you are using in the application, the Android build tooling will include only dependencies you actually need.

**Comment by Zane-cqupt** [comment]
Thank u, I will have another try

**Comment by emicklei** [comment]
Can this issue be closed?

**Comment by Zane96** [comment]
Sure, thank u very much！
